name: Luma
options:
  bundleIdPrefix: com.luma
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "26.2"
  defaultConfig: Release

configFiles:
  Debug: Signing.xcconfig
  Release: Signing.xcconfig

targets:
  Luma:
    type: application
    platform: macOS
    sources:
      - path: Luma
    settings:
      base:
        PRODUCT_NAME: Luna
        PRODUCT_BUNDLE_IDENTIFIER: com.luma.browser
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Luma/Luma.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Luna
        INFOPLIST_KEY_CFBundleName: Luna
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_NSBluetoothWhileInUseUsageDescription: "Luma needs Bluetooth access for compatible devices."
        INFOPLIST_KEY_NSCameraUsageDescription: "Luma needs camera access for websites that request it."
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Luma needs microphone access for websites that request it."
        INFOPLIST_KEY_NSDownloadsFolderUsageDescription: "Luma needs access to Downloads to save files."
        ENABLE_APP_SANDBOX: YES
        ENABLE_INCOMING_NETWORK_CONNECTIONS: NO
        ENABLE_OUTGOING_NETWORK_CONNECTIONS: YES
        ENABLE_PREVIEWS: YES
        ENABLE_RESOURCE_ACCESS_AUDIO_INPUT: YES
        ENABLE_RESOURCE_ACCESS_BLUETOOTH: YES
        ENABLE_RESOURCE_ACCESS_CALENDARS: NO
        ENABLE_RESOURCE_ACCESS_CAMERA: YES
        ENABLE_RESOURCE_ACCESS_CONTACTS: NO
        ENABLE_RESOURCE_ACCESS_LOCATION: NO
        ENABLE_RESOURCE_ACCESS_PRINTING: NO
        ENABLE_RESOURCE_ACCESS_USB: YES
        ENABLE_USER_SELECTED_FILES: readonly
        REGISTER_APP_GROUPS: YES
        STRING_CATALOG_GENERATE_SYMBOLS: YES
        SWIFT_APPROACHABLE_CONCURRENCY: YES
        SWIFT_DEFAULT_ACTOR_ISOLATION: MainActor
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_UPCOMING_FEATURE_MEMBER_IMPORT_VISIBILITY: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
