// Luma MVP - autogenerated by Cursor
import Foundation

/// Routes parsed LLM responses to deterministic browser actions.
/// 
/// Per AGENTS.md: Model output is a proposal. The app decides what can happen.
/// This router performs deterministic mapping only; no LLM calls.
/// Per SRS F4: Actions are allowlisted and executed exactly once.
final class CommandRouter {
    
    /// Parses JSON data into an LLMResponse.
    /// Returns nil if decoding fails (fail closed per AGENTS.md).
    func parseLLMResponse(_ data: Data) -> LLMResponse? {
        let decoder = JSONDecoder()
        return try? decoder.decode(LLMResponse.self, from: data)
    }
    
    /// Executes a browser action by mapping it to TabManager calls.
    /// Per AGENTS.md: Fail closed - if payload missing required fields, return error.
    /// Returns success message or error.
    func execute(action: BrowserAction, tabManager: TabManager) -> Result<String, Error> {
        switch action.type {
        case .new_tab:
            let url: URL?
            if let urlString = action.payload?["url"] {
                url = URL(string: urlString)
            } else {
                url = nil
            }
            let tabId = tabManager.newTab(url: url)
            return .success("Created new tab: \(tabId.uuidString)")
            
        case .navigate:
            guard let urlString = action.payload?["url"] else {
                return .failure(CommandRouterError.missingPayloadField("url"))
            }
            guard let url = URL(string: urlString) else {
                return .failure(CommandRouterError.invalidURL(urlString))
            }
            tabManager.navigateCurrentTab(to: url)
            return .success("Navigated to: \(urlString)")
            
        case .switch_tab:
            guard let tabIdString = action.payload?["index"] else {
                return .failure(CommandRouterError.missingPayloadField("index"))
            }
            // Note: In MVP, we use UUID strings, not indices. For now, parse as UUID.
            // Future: may need to map index to UUID if LLM provides index.
            guard let tabId = UUID(uuidString: tabIdString) else {
                return .failure(CommandRouterError.invalidTabID(tabIdString))
            }
            tabManager.switchToTab(tabId)
            return .success("Switched to tab: \(tabIdString)")
            
        case .close_tab:
            if let tabIdString = action.payload?["index"] {
                guard let tabId = UUID(uuidString: tabIdString) else {
                    return .failure(CommandRouterError.invalidTabID(tabIdString))
                }
                tabManager.closeTab(tabId)
                return .success("Closed tab: \(tabIdString)")
            } else {
                // Close current tab if no index specified
                guard let currentId = tabManager.currentTab else {
                    return .failure(CommandRouterError.noCurrentTab)
                }
                tabManager.closeTab(currentId)
                return .success("Closed current tab: \(currentId.uuidString)")
            }
        }
    }
}

/// Errors that can occur during action execution.
enum CommandRouterError: LocalizedError {
    case missingPayloadField(String)
    case invalidURL(String)
    case invalidTabID(String)
    case noCurrentTab
    
    var errorDescription: String? {
        switch self {
        case .missingPayloadField(let field):
            return "Missing required payload field: \(field)"
        case .invalidURL(let url):
            return "Invalid URL: \(url)"
        case .invalidTabID(let id):
            return "Invalid tab ID: \(id)"
        case .noCurrentTab:
            return "No current tab to close"
        }
    }
}
