// Luma MVP - autogenerated by Cursor
import Foundation
import SwiftUI
import AppKit

/// Right-side AI command panel (Cmd+E toggle). Per-tab chat with history.
///
/// Per SRS F2: Toggled via Cmd+E, dockable and dismissible.
/// Per AGENTS.md: AI is user-invoked only; no background activity.
/// Per SECURITY.md: UI must display what will be sent and require confirmation.
struct CommandSurfaceView: View {
    @Binding var isPresented: Bool
    @Binding var messages: [ChatMessage]
    let webViewWrapper: WebViewWrapper
    let commandRouter: CommandRouter
    let gemini: GeminiClient
    let onActionProposed: (LLMResponse) -> Void

    @State private var inputText: String = ""
    @State private var errorMessage: String? = nil
    @State private var isSending: Bool = false
    @State private var actionProposedMessage: String? = nil
    @State private var includeSelection: Bool = false
    @State private var selectedText: String? = nil
    @State private var whatWillBeSentExpanded: Bool = false

    // Auto-loaded page context
    @State private var pageTitle: String? = nil
    @State private var pageText: String? = nil
    @State private var isLoadingContext: Bool = false
    @State private var contextRefreshTimer: Timer? = nil

    private let accent = Color.accentColor

    var body: some View {
        VStack(spacing: 0) {
            // Header: Luma + status dot + optional Settings + close (small, calm)
            HStack(spacing: 8) {
                Text("Luma")
                    .font(.system(size: 13, weight: .semibold))
                statusDotView()
                if KeychainManager.shared.fetchGeminiKey() == nil || GeminiClient.lastNetworkError != nil {
                    SettingsLink { Text("Settings").font(.caption2).foregroundStyle(.secondary) }
                        .buttonStyle(.plain)
                }
                Spacer()
                Button(action: close) {
                    Image(systemName: "xmark")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundStyle(.secondary)
                }
                .buttonStyle(.plain)
                .keyboardShortcut(.escape, modifiers: [])
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 10)
            .background(.ultraThinMaterial)

            // Collapsible "What will be sent" (off by default)
            DisclosureGroup(isExpanded: $whatWillBeSentExpanded) {
                contextPreviewContent()
                    .font(.system(size: 11))
                    .padding(.top, 4)
            } label: {
                Text("What will be sent")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 6)
            .background(.ultraThinMaterial.opacity(0.6))

            // Chat history (scrollable, smaller font)
            ScrollViewReader { proxy in
                ScrollView {
                    LazyVStack(alignment: .leading, spacing: 10) {
                        ForEach(messages) { msg in
                            ChatBubble(message: msg, isUser: msg.role == .user)
                        }
                    }
                    .padding(12)
                }
                .frame(maxHeight: .infinity)
                .onChange(of: messages.count) { _, _ in
                    if let last = messages.last {
                        withAnimation(.easeOut(duration: 0.18)) {
                            proxy.scrollTo(last.id, anchor: .bottom)
                        }
                    }
                }
            }

            // Input area: small multi-line (up to 4 lines) + paper plane + toggles
            VStack(spacing: 6) {
                HStack(alignment: .bottom, spacing: 8) {
                    GrowingTextEditor(
                        text: $inputText,
                        placeholder: "Message...",
                        minHeight: 32
                    )
                    .padding(8)
                    .frame(maxHeight: 80)
                    .background(.ultraThinMaterial)
                    .clipShape(RoundedRectangle(cornerRadius: 10))

                    Button(action: sendCommand) {
                        Image(systemName: "paperplane.fill")
                            .font(.system(size: 14))
                            .foregroundColor(inputText.isEmpty ? .secondary.opacity(0.5) : accent)
                    }
                    .buttonStyle(.plain)
                    .disabled(inputText.isEmpty || isSending)
                    .keyboardShortcut(.return, modifiers: .command)
                    .help("Send (⌘↵)")
                }

                HStack(spacing: 12) {
                    Toggle(isOn: $includeSelection) {
                        Text("Include selection")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                    .toggleStyle(.checkbox)
                    .onChange(of: includeSelection) { _, on in
                        if on { fetchSelectedText() }
                        else { selectedText = nil }
                    }

                    if let msg = actionProposedMessage {
                        Text(msg)
                            .font(.caption2)
                            .foregroundStyle(.secondary)
                    }
                    if let err = errorMessage {
                        Text(err)
                            .font(.caption2)
                            .foregroundColor(.red)
                            .lineLimit(1)
                    }
                    Spacer(minLength: 0)
                }
            }
            .padding(12)
            .background(.ultraThinMaterial)
        }
        .background(.regularMaterial)
        .onAppear {
            loadPageContext()
            startContextRefreshTimer()
        }
        .onDisappear {
            stopContextRefreshTimer()
        }
    }

    @ViewBuilder
    private func statusDotView() -> some View {
        let (color, _) = statusDotState()
        Circle()
            .fill(color)
            .frame(width: 6, height: 6)
    }

    private func statusDotState() -> (Color, String) {
        if GeminiClient.lastNetworkError != nil {
            return (.red, "Error")
        }
        if KeychainManager.shared.fetchGeminiKey() == nil {
            return (.gray, "No key")
        }
        return (.green, "Ready")
    }

    private func sendIfEnter() {
        if !inputText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            sendCommand()
        }
    }

    private struct ChatBubble: View {
        let message: ChatMessage
        let isUser: Bool

        var body: some View {
            HStack {
                if isUser { Spacer(minLength: 32) }
                Text(message.text)
                    .font(.system(size: 12))
                    .foregroundColor(isUser ? .white : .primary)
                    .padding(.horizontal, 10)
                    .padding(.vertical, 6)
                    .background(isUser ? Color.accentColor : Color.primary.opacity(0.06))
                    .clipShape(RoundedRectangle(cornerRadius: 10))
                if !isUser { Spacer(minLength: 32) }
            }
        }
    }

    private func fetchSelectedText() {
        webViewWrapper.evaluateSelectedText { text in
            selectedText = text
        }
    }

    @ViewBuilder
    private func contextPreviewContent() -> some View {
        VStack(alignment: .leading, spacing: 4) {
            if let url = webViewWrapper.currentURL {
                Text("URL: \(url.absoluteString)")
                    .lineLimit(1)
            }
            if let title = pageTitle, !title.isEmpty {
                Text("Title: \(title)")
                    .lineLimit(1)
            }
            if let text = pageText, !text.isEmpty {
                Text("Page: \(text.prefix(200))\(text.count > 200 ? "…" : "")")
                    .lineLimit(3)
            }
            if includeSelection, let sel = selectedText, !sel.isEmpty {
                Text("Selection: \(sel.prefix(100))\(sel.count > 100 ? "…" : "")")
                    .lineLimit(2)
            }
            if isLoadingContext {
                ProgressView()
                    .scaleEffect(0.6)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private func close() {
        stopContextRefreshTimer()
        isPresented = false
        inputText = ""
        errorMessage = nil
        isSending = false
        actionProposedMessage = nil
    }

    /// Starts a timer to refresh context every 3 seconds.
    private func startContextRefreshTimer() {
        stopContextRefreshTimer()
        contextRefreshTimer = Timer.scheduledTimer(withTimeInterval: 3.0, repeats: true) { _ in
            loadPageContext()
        }
    }

    /// Stops the context refresh timer.
    private func stopContextRefreshTimer() {
        contextRefreshTimer?.invalidate()
        contextRefreshTimer = nil
    }

    /// Loads page context (title + visible text) when panel appears.
    private func loadPageContext() {
        isLoadingContext = true
        let group = DispatchGroup()

        group.enter()
        webViewWrapper.evaluatePageTitle { title in
            pageTitle = title
            group.leave()
        }

        group.enter()
        webViewWrapper.evaluateVisibleText(maxChars: 4000) { text in
            pageText = text
            group.leave()
        }

        group.notify(queue: .main) {
            isLoadingContext = false
        }
    }

    /// Builds context string from page metadata and optional selection.
    private func buildContextString() -> String? {
        var parts: [String] = []

        if let url = webViewWrapper.currentURL {
            parts.append("URL: \(url.absoluteString)")
        }

        if let title = pageTitle, !title.isEmpty {
            parts.append("Title: \(title)")
        }

        if let text = pageText, !text.isEmpty {
            parts.append("Page content:\n\(text)")
        }

        if includeSelection, let sel = selectedText, !sel.isEmpty {
            parts.append("Selection:\n\(sel)")
        }

        return parts.isEmpty ? nil : parts.joined(separator: "\n")
    }

    private func sendCommand() {
        let trimmed = inputText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        isSending = true
        errorMessage = nil
        actionProposedMessage = nil

        let userMsg = ChatMessage(role: .user, text: trimmed)
        messages.append(userMsg)
        inputText = ""

        // Always include page context
        let context = buildContextString()
        proceedWithSend(prompt: trimmed, context: context)
    }

    private func proceedWithSend(prompt: String, context: String?) {
        let promptToSend = prompt
        let contextToSend = context

        gemini.generate(prompt: promptToSend, context: contextToSend) { result in
            DispatchQueue.main.async {
                isSending = false

                switch result {
                case .success(let data):
                    if let response = try? JSONDecoder().decode(LLMResponse.self, from: data) {
                        messages.append(ChatMessage(role: .assistant, text: response.text))
                        if response.action != nil {
                            onActionProposed(response)
                            actionProposedMessage = "Action proposed"
                        }
                    } else {
                        errorMessage = "Failed to parse response"
                    }

                case .failure(let error):
                    let msg = error.localizedDescription
                    errorMessage = msg
                    messages.append(ChatMessage(role: .assistant, text: "Error: \(msg)"))
                    actionProposedMessage = nil
                }
            }
        }
    }
}

// MARK: - Growing multiline text editor

private struct TextHeightKey: PreferenceKey {
    static var defaultValue: CGFloat = 0
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = nextValue()
    }
}

private struct GrowingTextEditor: View {
    @Binding var text: String
    var placeholder: String
    var minHeight: CGFloat

    /// Height from content; no upper bound so the whole query is visible.
    @State private var contentHeight: CGFloat = 36

    private let font = Font.system(size: 13)

    private var boxHeight: CGFloat {
        max(minHeight, contentHeight)
    }

    var body: some View {
        ZStack(alignment: .topLeading) {
            // Measure content height using invisible text (opacity 0 so no double-text overlay)
            Text(text.isEmpty ? " " : text)
                .font(font)
                .frame(maxWidth: .infinity, alignment: .topLeading)
                .fixedSize(horizontal: false, vertical: true)
                .padding(8)
                .opacity(0)
                .background(
                    GeometryReader { g in
                        Color.clear.preference(key: TextHeightKey.self, value: g.size.height)
                    }
                )
                .allowsHitTesting(false)

            TextEditor(text: $text)
                .font(font)
                .scrollContentBackground(.hidden)
                .padding(4)
                .frame(minHeight: minHeight, maxHeight: .infinity)
                .frame(height: boxHeight)

            if text.isEmpty {
                Text(placeholder)
                    .font(font)
                    .foregroundStyle(.secondary)
                    .padding(12)
                    .frame(maxWidth: .infinity, alignment: .topLeading)
                    .frame(height: boxHeight)
                    .allowsHitTesting(false)
            }
        }
        .frame(height: boxHeight)
        .onPreferenceChange(TextHeightKey.self) { h in
            contentHeight = max(minHeight, h)
        }
    }
}
