// Luma MVP - autogenerated by Cursor
import Foundation

/// Allowed browser action types per AGENTS.md Browser Action Allowlist.
enum ActionType: String, Codable {
    case new_tab
    case navigate
    case switch_tab
    case close_tab
}

/// Represents a deterministic browser action parsed from LLM response.
/// Per AGENTS.md: Actions must be from a strict allowlist and executed exactly once.
struct BrowserAction: Codable, Identifiable {
    let id: UUID
    let type: ActionType
    let payload: [String: String]?
}

/// LLM response containing text and optional browser action.
struct LLMResponse: Codable {
    let text: String
    let action: BrowserAction?
}
