// Luma MVP - autogenerated by Cursor
import SwiftUI
import WebKit
import AppKit
import Combine

/// Minimal browser shell hosting WKWebViews via WebViewWrapper and TabManager.
///
/// Per SRS: WebKit-only renderer, minimal tab UI, address bar.
/// Omnibox: accepts full URL, domain, or search query.
/// Per SECURITY.md: No JS message handlers, no HTML scraping.
struct BrowserShellView: View {
    @StateObject private var tabManager = TabManager()
    @StateObject private var web = WebViewWrapper()
    @State private var addressBarText: String = ""
    @State private var tabsWithPanelOpen: Set<UUID> = []
    @State private var tabChatHistory: [UUID: [ChatMessage]] = [:]
    @State private var aiPanelWidth: CGFloat = 360
    @State private var eventMonitor: Any?
    @State private var pendingAction: BrowserAction? = nil
    @State private var pendingAssistantText: String = ""
    @State private var showActionConfirm: Bool = false
    @State private var showHistorySheet: Bool = false
    @FocusState private var addressBarFocused: Bool

    private let router = CommandRouter()
    private let gemini = GeminiClient(apiKeyProvider: { KeychainManager.shared.fetchGeminiKey() })

    private let tabBarHeight: CGFloat = 40

    var body: some View {
        HStack(spacing: 0) {
            VStack(spacing: 0) {
                // Unified top chrome: tabs + address bar + nav
                HStack(spacing: 0) {
                    // Tab strip (pill-shaped, scrollable)
                    ScrollView(.horizontal, showsIndicators: false) {
                        ScrollViewReader { proxy in
                            HStack(spacing: 4) {
                                ForEach(Array(tabManager.tabOrder.enumerated()), id: \.element) { index, tabId in
                                    TabPill(
                                        tabId: tabId,
                                        index: index + 1,
                                        url: tabManager.tabURL[tabId] ?? nil,
                                        isActive: tabManager.currentTab == tabId,
                                        onSelect: { switchToTab(tabId) },
                                        onClose: { closeTab(tabId) }
                                    )
                                    .id(tabId)
                                }
                            }
                            .padding(.horizontal, 8)
                            .padding(.vertical, 6)
                        }
                    }
                    .frame(minWidth: 80, maxWidth: 280)

                    // Address bar (continuous strip from tabs)
                    HStack(spacing: 6) {
                        Button(action: { if let id = tabManager.currentTab { web.goBack(in: id) } }) {
                            Image(systemName: "chevron.left")
                                .font(.system(size: 12, weight: .medium))
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("Back")

                        Button(action: { if let id = tabManager.currentTab { web.goForward(in: id) } }) {
                            Image(systemName: "chevron.right")
                                .font(.system(size: 12, weight: .medium))
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("Forward")

                        Button(action: { if let id = tabManager.currentTab { web.reload(in: id) } }) {
                            Image(systemName: "arrow.clockwise")
                                .font(.system(size: 12, weight: .medium))
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("Reload")

                        TextField("Search or enter URL", text: $addressBarText, onCommit: goToAddress)
                            .textFieldStyle(.plain)
                            .focused($addressBarFocused)
                            .padding(.horizontal, 10)
                            .padding(.vertical, 6)
                            .background(Color(nsColor: .textBackgroundColor).opacity(0.6))
                            .cornerRadius(6)

                        Button("Go", action: goToAddress)
                            .buttonStyle(.bordered)
                            .controlSize(.small)

                        Button(action: newTab) {
                            Image(systemName: "plus")
                                .font(.system(size: 12, weight: .medium))
                        }
                        .buttonStyle(.plain)
                        .accessibilityLabel("New tab")
                    }
                    .padding(.horizontal, 8)
                    .padding(.vertical, 6)
                }
                .frame(height: tabBarHeight)
                .background(.ultraThinMaterial)

                // Main content (flush under chrome)
                if let currentId = tabManager.currentTab {
                    WebViewContainer(webView: web.ensureWebView(for: currentId))
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .id(currentId)
                } else {
                    Color(nsColor: .windowBackgroundColor)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .overlay(Text("No tab").foregroundColor(.secondary))
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)

            if let currentId = tabManager.currentTab, tabsWithPanelOpen.contains(currentId) {
                HStack(spacing: 0) {
                    // Resize handle (drag left edge to resize panel)
                    PanelResizeHandle(panelWidth: $aiPanelWidth)

                    CommandSurfaceView(
                        isPresented: Binding(
                            get: { tabsWithPanelOpen.contains(currentId) },
                            set: { if !$0 { tabsWithPanelOpen.remove(currentId) } }
                        ),
                        messages: Binding(
                            get: { tabChatHistory[currentId] ?? [] },
                            set: { tabChatHistory[currentId] = $0 }
                        ),
                        webViewWrapper: web,
                        commandRouter: router,
                        gemini: gemini
                    ) { response in
                        pendingAssistantText = response.text
                        pendingAction = response.action
                        showActionConfirm = (response.action != nil)
                    }
                    .frame(width: aiPanelWidth)
                    .background(Color(red: 0.08, green: 0.08, blue: 0.1))
                    .shadow(color: .black.opacity(0.3), radius: 8, x: -2, y: 0)
                }
            }
        }
        .alert("Confirm Action", isPresented: $showActionConfirm) {
            Button("Cancel", role: .cancel) { pendingAction = nil }
            Button("Execute") { executePendingAction() }
        } message: {
            if let action = pendingAction {
                let typeText = action.type.rawValue
                let payloadKeys = action.payload?.keys.sorted() ?? []
                let payloadSummary = payloadKeys.isEmpty ? "none" : payloadKeys.joined(separator: ", ")
                Text("Assistant: \(pendingAssistantText)\n\nAction: \(typeText)\nPayload keys: \(payloadSummary)")
            } else {
                Text("No action to execute.")
            }
        }
        .sheet(isPresented: $showHistorySheet) {
            HistoryView(
                entries: tabManager.navigationHistory,
                onSelect: { url in
                    showHistorySheet = false
                    if let id = tabManager.currentTab {
                        web.load(url: url, in: id)
                        tabManager.navigate(tab: id, to: url)
                        addressBarText = url.absoluteString
                    }
                },
                onDismiss: { showHistorySheet = false }
            )
        }
        .onAppear {
            if tabManager.currentTab == nil {
                let url = URL(string: "https://example.com")!
                let id = tabManager.newTab(url: url)
                _ = web.ensureWebView(for: id)
                web.setActiveTab(id)
                web.load(url: url, in: id)
                tabManager.addNavigation(title: url.host ?? url.absoluteString, url: url)
                addressBarText = url.absoluteString
            }
            eventMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
                let key = event.charactersIgnoringModifiers ?? ""
                if event.modifierFlags.contains(.command) {
                    if key == "e" {
                        DispatchQueue.main.async {
                            guard let id = tabManager.currentTab else { return }
                            if tabsWithPanelOpen.contains(id) {
                                tabsWithPanelOpen.remove(id)
                            } else {
                                tabsWithPanelOpen.insert(id)
                            }
                        }
                        return nil
                    }
                    if key == "t" {
                        DispatchQueue.main.async { newTab() }
                        return nil
                    }
                    if key == "w" {
                        DispatchQueue.main.async { closeCurrentTab() }
                        return nil
                    }
                    if key == "y" {
                        DispatchQueue.main.async { showHistorySheet = true }
                        return nil
                    }
                }
                return event
            }
        }
        .onChange(of: tabManager.currentTab) { _, newId in
            if let id = newId {
                web.setActiveTab(id)
                syncAddressBarFromCurrentTab()
            } else {
                addressBarText = ""
            }
        }
        .onChange(of: web.currentURL) { _, _ in
            syncAddressBarFromCurrentTab()
        }
        .onDisappear {
            if let m = eventMonitor {
                NSEvent.removeMonitor(m)
                eventMonitor = nil
            }
        }
    }

    private func syncAddressBarFromCurrentTab() {
        if let id = tabManager.currentTab {
            if let url = web.currentURL {
                addressBarText = url.absoluteString
                tabManager.navigate(tab: id, to: url)
            } else if let url = tabManager.tabURL[id] ?? nil {
                addressBarText = url.absoluteString
            } else {
                addressBarText = ""
            }
        } else {
            addressBarText = ""
        }
    }

    /// Omnibox parsing: URL, domain, or search query.
    private func resolveToURL(_ input: String) -> URL? {
        let trimmed = input.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        if trimmed.lowercased().hasPrefix("http://") || trimmed.lowercased().hasPrefix("https://") {
            return URL(string: trimmed)
        }

        if !trimmed.contains(" "), trimmed.contains(".") {
            return URL(string: "https://" + trimmed)
        }

        let encoded = trimmed.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? trimmed
        return URL(string: "https://www.google.com/search?q=" + encoded)
    }

    private func goToAddress() {
        guard let url = resolveToURL(addressBarText) else { return }

        let title = url.host ?? url.absoluteString
        if tabManager.currentTab == nil {
            let id = tabManager.newTab(url: url)
            _ = web.ensureWebView(for: id)
            web.setActiveTab(id)
            web.load(url: url, in: id)
        } else if let id = tabManager.currentTab {
            tabManager.navigate(tab: id, to: url)
            web.load(url: url, in: id)
        }
        tabManager.addNavigation(title: title, url: url)
        addressBarText = url.absoluteString
    }

    private func newTab() {
        let id = tabManager.newTab(url: nil)
        _ = web.ensureWebView(for: id)
        web.setActiveTab(id)
        addressBarText = ""
        addressBarFocused = true
    }

    private func closeCurrentTab() {
        guard let id = tabManager.currentTab else { return }
        closeTab(id)
    }

    private func closeTab(_ id: UUID) {
        web.removeWebView(for: id)
        tabsWithPanelOpen.remove(id)
        tabChatHistory.removeValue(forKey: id)
        tabManager.closeTab(id)
        if tabManager.currentTab == nil {
            newTab()
        } else if let newCurrent = tabManager.currentTab {
            web.setActiveTab(newCurrent)
            syncAddressBarFromCurrentTab()
        }
    }

    private func switchToTab(_ id: UUID) {
        tabManager.switchToTab(id)
        web.setActiveTab(id)
        syncAddressBarFromCurrentTab()
    }


    private func executePendingAction() {
        guard let action = pendingAction else { return }

        let tabToClose: UUID?
        if action.type == .close_tab, action.payload?["index"] == nil {
            tabToClose = tabManager.currentTab
        } else {
            tabToClose = nil
        }

        let result = router.execute(action: action, tabManager: tabManager)
        switch result {
        case .success:
            if let id = tabToClose {
                web.removeWebView(for: id)
            }
            if action.type == .new_tab || action.type == .navigate,
               let urlString = action.payload?["url"],
               let url = URL(string: urlString.contains("://") ? urlString : "https://" + urlString) {
                if action.type == .new_tab, let id = tabManager.currentTab {
                    web.setActiveTab(id)
                    web.load(url: url, in: id)
                    tabManager.navigate(tab: id, to: url)
                    addressBarText = url.absoluteString
                } else if action.type == .navigate, let id = tabManager.currentTab {
                    web.load(url: url, in: id)
                    tabManager.navigateCurrentTab(to: url)
                    addressBarText = url.absoluteString
                }
            }
        case .failure:
            break
        }

        pendingAction = nil
    }
}

// MARK: - History sheet (Cmd+Y)

private struct HistoryView: View {
    let entries: [HistoryEntry]
    let onSelect: (URL) -> Void
    let onDismiss: () -> Void

    private static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .short
        f.timeStyle = .short
        return f
    }()

    var body: some View {
        VStack(spacing: 0) {
            HStack {
                Text("History")
                    .font(.headline)
                Spacer()
                Button("Done", action: onDismiss)
                    .keyboardShortcut(.escape, modifiers: [])
            }
            .padding()

            Divider()

            if entries.isEmpty {
                Text("No history yet")
                    .foregroundColor(.secondary)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                List(entries) { entry in
                    Button {
                        onSelect(entry.url)
                    } label: {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(entry.title)
                                .lineLimit(1)
                                .font(.system(size: 13, weight: .medium))
                            Text(entry.url.absoluteString)
                                .lineLimit(1)
                                .font(.caption)
                                .foregroundColor(.secondary)
                            Text(Self.dateFormatter.string(from: entry.date))
                                .font(.caption2)
                                .foregroundColor(.secondary.opacity(0.8))
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.vertical, 4)
                    }
                    .buttonStyle(.plain)
                }
                .listStyle(.plain)
            }
        }
        .frame(minWidth: 400, minHeight: 300)
    }
}

private struct PanelResizeHandle: View {
    @Binding var panelWidth: CGFloat

    private let minWidth: CGFloat = 280
    private let maxWidth: CGFloat = 700
    @State private var dragStartWidth: CGFloat = 0

    var body: some View {
        Rectangle()
            .fill(Color.clear)
            .frame(width: 6)
            .contentShape(Rectangle())
            .onHover { hovering in
                if hovering {
                    NSCursor.resizeLeftRight.push()
                } else {
                    NSCursor.pop()
                }
            }
            .gesture(
                DragGesture()
                    .onChanged { value in
                        if dragStartWidth == 0 {
                            dragStartWidth = panelWidth
                        }
                        let newWidth = dragStartWidth - value.translation.width
                        panelWidth = min(maxWidth, max(minWidth, newWidth))
                    }
                    .onEnded { _ in
                        dragStartWidth = 0
                    }
            )
    }
}

private struct TabPill: View {
    let tabId: UUID
    let index: Int
    let url: URL?
    let isActive: Bool
    let onSelect: () -> Void
    let onClose: () -> Void

    @State private var isHovered = false

    private var title: String {
        url?.host ?? url?.absoluteString ?? "New Tab"
    }

    var body: some View {
        HStack(spacing: 4) {
            Button(action: onSelect) {
                Text(title)
                    .lineLimit(1)
                    .truncationMode(.tail)
                    .font(.system(size: 12))
                    .frame(maxWidth: 140)
            }
            .buttonStyle(.plain)
            .padding(.leading, 8)
            .padding(.trailing, isHovered ? 4 : 8)
            .padding(.vertical, 6)

            if isHovered {
                Button(action: onClose) {
                    Image(systemName: "xmark")
                        .font(.system(size: 9, weight: .semibold))
                        .foregroundColor(.secondary)
                        .frame(width: 16, height: 16)
                }
                .buttonStyle(.plain)
                .padding(.trailing, 6)
                .accessibilityLabel("Close tab")
            }
        }
        .background(
            RoundedRectangle(cornerRadius: 8)
                .fill(isActive ? Color.accentColor.opacity(0.25) : (isHovered ? Color.primary.opacity(0.06) : Color.clear))
        )
        .overlay(
            RoundedRectangle(cornerRadius: 8)
                .stroke(isActive ? Color.accentColor.opacity(0.3) : Color.clear, lineWidth: 1)
        )
        .shadow(color: .black.opacity(isActive ? 0.06 : 0), radius: 2, y: 1)
        .scaleEffect(isHovered && !isActive ? 1.02 : 1.0)
        .animation(.easeOut(duration: 0.15), value: isHovered)
        .animation(.easeOut(duration: 0.15), value: isActive)
        .onHover { hovering in
            isHovered = hovering
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Tab \(index): \(title)")
        .accessibilityAddTraits(isActive ? [.isButton, .isSelected] : .isButton)
    }
}

struct WebViewContainer: NSViewRepresentable {
    let webView: WKWebView

    func makeNSView(context: Context) -> WKWebView { webView }
    func updateNSView(_ nsView: WKWebView, context: Context) {}
}

#Preview {
    BrowserShellView()
}
