// Luma MVP - autogenerated by Cursor
import Foundation
import SwiftUI
import Combine

/// Manages browser tab lifecycle and navigation state.
///
/// Per SRS F1 and AGENTS.md: All browser actions must be deterministic and visible.
/// No persistence in MVP (SRS 2.3).
final class TabManager: ObservableObject {
    @Published var tabOrder: [UUID] = []
    @Published var tabURL: [UUID: URL?] = [:]
    @Published var currentTab: UUID? = nil

    func newTab(url: URL?) -> UUID {
        let id = UUID()
        tabOrder.append(id)
        tabURL[id] = url
        currentTab = id
        return id
    }

    func closeTab(_ id: UUID) {
        let wasCurrent = (currentTab == id)
        let closedIdx = tabOrder.firstIndex(of: id)

        tabOrder.removeAll { $0 == id }
        tabURL.removeValue(forKey: id)

        if wasCurrent, let idx = closedIdx {
            if idx > 0 {
                currentTab = tabOrder[idx - 1]
            } else if !tabOrder.isEmpty {
                currentTab = tabOrder[0]
            } else {
                currentTab = nil
            }
        }
    }

    func switchToTab(_ id: UUID) {
        guard tabOrder.contains(id) else { return }
        currentTab = id
    }

    func navigate(tab id: UUID, to url: URL) {
        guard tabOrder.contains(id) else { return }
        tabURL[id] = url
    }

    func navigateCurrentTab(to url: URL) {
        guard let currentId = currentTab else { return }
        tabURL[currentId] = url
    }

    func currentURL() -> URL? {
        guard let id = currentTab else { return nil }
        return tabURL[id] ?? nil
    }

    func currentIndex() -> Int? {
        guard let id = currentTab else { return nil }
        return tabOrder.firstIndex(of: id)
    }

    func tabCount() -> Int {
        tabOrder.count
    }
}
