// Luma MVP - autogenerated by Cursor
import Foundation
import WebKit
import SwiftUI
import Combine


/// Minimal, safe WKWebView host for Luma browser tabs.
/// 
/// Security constraints:
/// - Selected-text fetching is the only page-to-app extraction allowed; no full HTML dumps.
/// - Do not expose file system or credentials to web content.
/// - No JS bridge message handlers in MVP (minimal attack surface).
final class WebViewWrapper: NSObject, ObservableObject, WKNavigationDelegate {
    @Published var currentURL: URL?

    /// Called when navigation completes; used to sync address bar.
    var onURLChanged: ((URL?) -> Void)?

    private var webView: WKWebView!

    override init() {
        super.init()
        
        let configuration = WKWebViewConfiguration()
        // JavaScript is enabled by default for web content.
        // Do NOT add any userContentController message handlers in MVP (no JS bridge).
        configuration.websiteDataStore = .default()
        
        webView = WKWebView(frame: .zero, configuration: configuration)
        webView.navigationDelegate = self
    }
    
    /// Returns the underlying WKWebView for embedding in SwiftUI views.
    var view: WKWebView {
        webView
    }
    
    /// Loads the specified URL on the main thread.
    func load(url: URL) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            let request = URLRequest(url: url)
            self.webView.load(request)
        }
    }
    
    /// Evaluates selected text from the page using safe JavaScript.
    /// Returns only the text content (window.getSelection().toString()), not HTML.
    /// Completion handler runs on main thread.
    func evaluateSelectedText(completion: @escaping (String?) -> Void) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else {
                completion(nil)
                return
            }
            
            // Safe JS snippet: only gets selected text, no HTML or DOM access beyond selection.
            self.webView.evaluateJavaScript("window.getSelection().toString()") { result, error in
                DispatchQueue.main.async {
                    if error != nil {
                        completion(nil)
                        return
                    }
                    
                    if let text = result as? String, !text.isEmpty {
                        completion(text)
                    } else {
                        completion(nil)
                    }
                }
            }
        }
    }
    
    // MARK: - WKNavigationDelegate
    
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }
            self.currentURL = webView.url
            self.onURLChanged?(webView.url)
        }
    }
}
