// Luma MVP - autogenerated by Cursor
import Foundation
import SwiftUI
import AppKit

/// Settings view for API key management.
///
/// Per SRS F5: Settings UI for AI enable/disable, Gemini API key input.
/// Per SECURITY.md: Keys handled via KeychainManager only; UI never stores tokens directly.
struct SettingsView: View {
    @State private var keyInput: String = ""
    @State private var statusText: String = ""
    @State private var hasKey: Bool = false
    @State private var isProcessing: Bool = false
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Settings")
                .font(.largeTitle)
                .padding(.bottom)
            
            // Gemini API Key Section
            VStack(alignment: .leading, spacing: 12) {
                Text("Gemini API Key (BYO)")
                    .font(.headline)
                
                Text("Enter your Gemini API key. It will be stored securely in Keychain.")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                SecureField("Enter API key", text: $keyInput)
                    .textFieldStyle(.roundedBorder)
                    .disabled(isProcessing)
                
                // Read-only key status row
                Text("AI Status: " + (hasKey ? "Key stored" : "No API key"))
                    .font(.caption)
                    .foregroundColor(hasKey ? .green : .secondary)
                
                // Detailed status text
                if !statusText.isEmpty {
                    Text(statusText)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                
                HStack(spacing: 12) {
                    Button("Save Key") {
                        saveKey()
                    }
                    .disabled(isProcessing)
                    
                    Button("Delete Key") {
                        deleteKey()
                    }
                    .disabled(isProcessing || !hasKey)
                }
            }
            .padding()
            .background(Color.gray.opacity(0.1))
            .cornerRadius(8)
            
            Spacer()
        }
        .padding()
        .frame(width: 500, height: 400)
        .onAppear(perform: loadKeyStatus)
    }
    
    private func loadKeyStatus() {
        let existingKey = KeychainManager.shared.fetchGeminiKey()
        hasKey = (existingKey != nil)
        statusText = hasKey ? "Key stored in Keychain. AI Status: Ready." : "No Gemini key saved."
    }
    
    private func saveKey() {
        let trimmed = keyInput.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            statusText = "Key cannot be empty"
            return
        }
        
        isProcessing = true
        statusText = ""
        
        do {
            try KeychainManager.shared.storeGeminiKey(trimmed)
            hasKey = true
            keyInput = "" // Clear input field for security
            GeminiClient.clearClientCaches()
            statusText = "Key saved to Keychain. AI Status: Ready."
        } catch {
            statusText = "Error saving key: \(error.localizedDescription)"
        }
        
        isProcessing = false
    }
    
    private func deleteKey() {
        isProcessing = true
        statusText = ""
        
        do {
            try KeychainManager.shared.deleteGeminiKey()
            hasKey = false
            GeminiClient.clearClientCaches()
            statusText = "Key deleted. AI Status: No API key."
        } catch {
            statusText = "Error deleting key: \(error.localizedDescription)"
        }
        
        isProcessing = false
    }
}
