// Luma MVP - autogenerated by Cursor
import Foundation
import SwiftUI
import AppKit
import AuthenticationServices
import Combine

/// Manages Supabase authentication via Google OAuth.
/// 
/// Per SRS 7: Authentication is optional; users can browse and use BYO AI features while signed out.
/// Per SRS 7.3: Sign-in is explicitly user-initiated; no automatic authentication.
/// Per SECURITY.md: OAuth tokens and Supabase session data must not be logged.
/// Per SECURITY.md: Authentication credentials must not be accessible to WKWebView or renderer JavaScript.
/// 
/// IMPORTANT: Do NOT delete Gemini BYO key on sign-out. Authentication and API key management are separate.
final class SupabaseAuth: ObservableObject {
    
    static let shared = SupabaseAuth()
    
    @Published var isSignedIn: Bool = false
    @Published var userEmail: String? = nil
    
    private init() {}
    
    // TODO: Inject Supabase configuration (from .env or secure config):
    // - supabaseURL: Supabase project URL (e.g., https://xxx.supabase.co)
    // - supabaseAnonKey: Supabase anonymous key
    // - googleClientID: Google OAuth client ID
    // - redirectURI: Custom URL scheme for OAuth callback (e.g., "com.luma.browser://oauth-callback")
    private var supabaseURL: String? = nil
    private var supabaseAnonKey: String? = nil
    private var googleClientID: String? = nil
    private var redirectURI: String? = nil
    
    /// Signs in with Google OAuth via Supabase.
    /// 
    /// Per SRS 7.2: Uses Supabase Auth as identity broker for Google OAuth.
    /// Per SRS 7.3: Sign-in is explicitly user-initiated.
    /// 
    /// Implementation flow (when configured):
    /// 1. Build Supabase OAuth URL: {supabaseURL}/auth/v1/authorize?provider=google&redirect_to={redirectURI}
    /// 2. Launch ASWebAuthenticationSession with the URL
    /// 3. User authenticates with Google in secure browser context
    /// 4. Google redirects to Supabase with authorization code
    /// 5. Supabase redirects to redirectURI with code and state parameters
    /// 6. Extract code from callback URL
    /// 7. Exchange code with Supabase REST API:
    ///    POST {supabaseURL}/auth/v1/token?grant_type=authorization_code
    ///    Body: { "code": code, "redirect_to": redirectURI }
    ///    Headers: { "apikey": supabaseAnonKey, "Content-Type": "application/json" }
    /// 8. Parse response to get access_token, refresh_token, user data
    /// 9. Store tokens securely in Keychain (separate from Gemini key)
    /// 10. Update isSignedIn and userEmail from response
    /// 
    /// Per SECURITY.md: Never expose tokens to web content or logs.
    /// 
    /// - Parameters:
    ///   - presentingWindow: The window to present the authentication session from
    ///   - completion: Callback with success or error
    func signInWithGoogle(presentingWindow: NSWindow, completion: @escaping (Result<Void, Error>) -> Void) {
        // Fail closed: require configuration
        guard let supabaseURL = supabaseURL,
              let supabaseAnonKey = supabaseAnonKey,
              let googleClientID = googleClientID,
              let redirectURI = redirectURI,
              let redirectURL = URL(string: redirectURI) else {
            completion(.failure(NotConfiguredError()))
            return
        }
        
        // TODO: Build OAuth URL and launch ASWebAuthenticationSession
        // For now, return NotConfiguredError as placeholder
        completion(.failure(NotConfiguredError()))
    }
    
    /// Signs out the current user.
    /// 
    /// Per SRS 7.3: Clears local session state immediately.
    /// Per SECURITY.md: Clears authentication tokens from Keychain.
    /// 
    /// IMPORTANT: Does NOT delete Gemini BYO key. That is managed separately by user.
    func signOut() {
        // TODO: Clear Supabase session tokens from Keychain (separate from Gemini key)
        // Do NOT call KeychainManager.shared.deleteGeminiKey() here
        
        isSignedIn = false
        userEmail = nil
    }
}

/// Error returned when Supabase/Google OAuth configuration is missing.
struct NotConfiguredError: LocalizedError {
    var errorDescription: String? {
        "Supabase authentication is not configured. Please configure Supabase URL, anon key, Google client ID, and redirect URI."
    }
}
