// Luma MVP - autogenerated by Cursor
import Foundation

final class DebugHarness {
    /// Quick verification test for CommandRouter parsing and execution.
    static func run() {
        let router = CommandRouter()
        let tabManager = TabManager()
        
        // Sample JSON response with action
        let sampleJSON = """
        {
            "text": "ok",
            "action": {
                "id": "\(UUID().uuidString)",
                "type": "navigate",
                "payload": {
                    "url": "https://example.com"
                }
            }
        }
        """
        
        guard let jsonData = sampleJSON.data(using: .utf8) else {
            print("DebugHarness: Failed to create JSON data")
            return
        }
        
        guard let response = router.parseLLMResponse(jsonData) else {
            print("DebugHarness: Failed to parse LLM response")
            return
        }
        
        print("DebugHarness: Parsed text: \(response.text)")
        
        if let action = response.action {
            let result = router.execute(action: action, tabManager: tabManager)
            switch result {
            case .success(let message):
                print("DebugHarness: Action executed successfully: \(message)")
            case .failure(let error):
                print("DebugHarness: Action execution failed: \(error.localizedDescription)")
            }
        } else {
            print("DebugHarness: No action in response")
        }
        
        // Test GeminiClient stub
        print("\nDebugHarness: Testing GeminiClient...")
        let geminiClient = GeminiClient(apiKeyProvider: { "test-key" })
        geminiClient.generate(prompt: "Test prompt", context: nil) { result in
            switch result {
            case .success(let data):
                print("DebugHarness: GeminiClient returned data: \(data.count) bytes")
                if let response = router.parseLLMResponse(data) {
                    print("DebugHarness: Parsed LLMResponse text: \(response.text)")
                }
            case .failure(let error):
                print("DebugHarness: GeminiClient error: \(error.localizedDescription)")
            }
        }
        
        // Test GeminiClient with nil key (should fail)
        let geminiClientNoKey = GeminiClient(apiKeyProvider: { nil })
        geminiClientNoKey.generate(prompt: "Test", context: nil) { result in
            switch result {
            case .success:
                print("DebugHarness: ERROR - Should have failed with no key")
            case .failure(let error):
                print("DebugHarness: Correctly failed with no key: \(error.localizedDescription)")
            }
        }
        
        // Test KeychainManager
        print("\nDebugHarness: Testing KeychainManager...")
        let keychain = KeychainManager.shared
        let testKey = "test-key-\(UUID().uuidString)" // Ephemeral test key, not a real secret
        
        // Store
        do {
            try keychain.storeGeminiKey(testKey)
            print("DebugHarness: Stored test key successfully")
        } catch {
            print("DebugHarness: Failed to store key: \(error.localizedDescription)")
            return
        }
        
        // Fetch
        if let fetchedKey = keychain.fetchGeminiKey() {
            if fetchedKey == testKey {
                print("DebugHarness: Fetched key matches stored key")
            } else {
                print("DebugHarness: ERROR - Fetched key does not match")
            }
        } else {
            print("DebugHarness: ERROR - Failed to fetch key")
        }
        
        // Delete
        do {
            try keychain.deleteGeminiKey()
            print("DebugHarness: Deleted test key successfully")
            
            // Verify deletion
            if keychain.fetchGeminiKey() == nil {
                print("DebugHarness: Verified key was deleted")
            } else {
                print("DebugHarness: ERROR - Key still exists after deletion")
            }
        } catch {
            print("DebugHarness: Failed to delete key: \(error.localizedDescription)")
        }
    }
}
